version: "3.3"
services:
  rabbitmq:
    hostname: "rabbitmq-dev"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    volumes:
      - /workspace/.rabbitmq/data/:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-dev
      - /workspace/.rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - openmusic

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /workspace/.redis/data:/data
    networks:
      - openmusic
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    command: |
      server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - /workspace/.minio/data:/data
      - /workspace/.minio/:/var/log/minio.log
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: ap-southeast-3
      MINIO_DOMAIN: s3.ap-southeast-3.amazonaws.com
      MINIO_HTTP_TRACE: /var/log/minio.log
    networks:
      - openmusic

networks:
  openmusic:
